# Welcome to Jekyll!
#
# Site settings
title: Apcension
description: |
  Cloud Based Solutions & Services

  inquiries@apcension.com
owner: Apcension, LLC # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: hosting@apcension.com
timezone: America/Los_Angeles
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.apcension.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/apcension
  github: https://github.com/apcension
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/Apcension/?view_public_for=228448270898126
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: inquiries@apcension.com
  #flickr:
  instagram: https://www.instagram.com/apcension/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
